export const customerDB = [
  {
    id: 1,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 2,
    name: "Ahmed Rosser",
    Description: "Lorem Ipsum Sit amet",
    Status: "Inactive",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 3,
    name: "Zain Calzoni",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 4,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Paid",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 5,
    name: "Ahmed Rosser",
    Description: "Lorem Ipsum Sit amet",
    Status: "Due",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 6,
    name: "Zain Calzoni",
    Description: "Lorem Ipsum Sit amet",
    Status: "Paid",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 7,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 8,
    name: "Ahmed Rosser",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 9,
    name: "Zain Calzoni",
    Description: "Lorem Ipsum Sit amet",
    Status: "Inactive",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 10,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 11,
    name: "Ahmed Rosser",
    Description: "Lorem Ipsum Sit amet",
    Status: "Due",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 12,
    name: "Zain Calzoni",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 13,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Paid",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 14,
    name: "Ahmed Rosser",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 15,
    name: "Zain Calzoni",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 16,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Due",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 17,
    name: "Ahmed Rosser",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
  {
    id: 18,
    name: "Zain Calzoni",
    Description: "Lorem Ipsum Sit amet",
    Status: "Paid",
    Rate: "$250.00",
    Balance: "-$150.00",
    Deposit: "$175.23",
  },
  {
    id: 19,
    name: "Ann Culhane",
    Description: "Lorem Ipsum Sit amet",
    Status: "Open",
    Rate: "$250.00",
    Balance: "$150.00",
    Deposit: "$175.23",
  },
];
